<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="TRD-LAP-007" failures="1" tests="5" name="Personal loan" time="0.178" errors="0" timestamp="2024-07-05T17:27:41 IST">
  <testcase classname="Framework_TestNG.day1" name="Demo" time="0.054">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
        <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Framework_TestNG.day1.Demo(day1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="Framework_TestNG.day2" name="ploan" time="0.002"/>
  <testcase classname="Framework_TestNG.day4" name="LoginAPIHomeLoan" time="0.003"/>
  <testcase classname="Framework_TestNG.day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="Framework_TestNG.day4" name="WebloginHomeLoan" time="0.003"/>
  <testcase classname="Framework_TestNG.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
